#!/bin/ash /etc/rc.common

START=99

start() {
        echo "Start Humidifier python" 
        python /root/AutomaticHumidifier/Script/UpdateSensor.py &  
        python /root/AutomaticHumidifier/Script/atomizer.py & 
        python /root/AutomaticHumidifier/Script/main.py & 

}

stop() {
        kill -9 `ps | grep "python /root/AutomaticHumidifier/Script/atomizer.py" | awk '{if(NR==1)print$1}'`
        kill -9 `ps | grep "python /root/AutomaticHumidifier/Script/main.py" | awk '{if(NR==1)print$1}'`
        kill -9 `ps | grep "python /root/AutomaticHumidifier/Script/UpdateSensor.py" | awk '{if(NR==1)print$1}'`

}
